### PR TITLE
Attempt to fix error when submitting empty file input

### LINKED ISSUE #83: Error when submitting form with empty file input
Hello,

I'm not sure if i'm posting on the right repository but I have an error when submitting a form with an empty file input:

`RuntimeException: Cannot retrieve stream due to upload error in /ppm/vendor/react/http/src/Io/UploadedFile.php:85`
`Stack trace:`
`#1 /ppm/vendor/php-pm/httpkernel-adapter/Bridges/HttpKernel.php(162): React\Http\Io\UploadedFile->getStream()`

It seems to happen because when submitting the form, browsers send the following param for the file:
`
Content-Disposition: form-data; name="author[photo]"; filename=""
Content-Type: application/octet-stream
`

Any idea on how to fix this ? 
Thanks

### PR DESCRIPTION
**Pull request by benjaminjonard**
Attempt to fix #83 

I used the function convertFileInformation from [this symfony file](https://github.com/symfony/http-foundation/blob/master/FileBag.php) as an example.

### CODE REVIEW

File: Bridges/HttpKernel.php [hunk 1]
```diff
@@ -159,15 +159,21 @@ protected function mapRequest(ServerRequestInterface $psrRequest)
...
-                    $value = new \Symfony\Component\HttpFoundation\File\UploadedFile(
-                        $tmpname,
-                        $value->getClientFilename(),
-                        $value->getClientMediaType(),
-                        $value->getSize(),
-                        $value->getError(),
-                        true
-                    );
+                    if (UPLOAD_ERR_NO_FILE == $value->getError()) {
+                        $value = null;
```
Comment (andig) [inline Bridges/HttpKernel.php]: Should rename `value` to `file` fr the entire loop.

File: Bridges/HttpKernel.php [hunk 2]
```diff
@@ -159,15 +159,21 @@ protected function mapRequest(ServerRequestInterface $psrRequest)
...
+                    } else {
+                        if (UPLOAD_ERR_OK == $value->getError()) {
+                            file_put_contents($tmpname, (string)$value->getStream());
+                        }
+                        $value = new \Symfony\Component\HttpFoundation\File\UploadedFile(
```
Comment (andig) [inline Bridges/HttpKernel.php]: `use ...UploadedFile as SymfonyFile`

**Comment by andig** [comment]
Please also check for Psr `UploadedFile`, not for React. Otherwise this should make perfect sense- much appreciated!

**Comment by andig** [comment]
Lgtm- much appreciated!
