### PR TITLE
Remove useless code and fix double headers overwriting

### LINKED ISSUE #47: Wrong headers
Hi! We have recently megred #46, but unfortunately, it brings a bug. When we call "add" method
https://github.com/php-pm/php-pm-httpkernel/blob/master/Bridges/HttpKernel.php#L183, we add headers from React request, but we can not track headers which were added by Symfony request from ServerBag. As it uses superglobal array $_SERVER, which only grows during application lifetime. For example:
I send regular http request, after that I send ajax request, all furtherst requests will have X-Request-With: XMLHttpRequest header. My propose is to return replace method, but move authorization headers from $_SERVER to $headers.

### PR DESCRIPTION
**Pull request by dzubchik**

### CODE REVIEW

File: Bridges/HttpKernel.php [hunk 1]
```diff
@@ -10,6 +10,7 @@
 use React\Http\Request as ReactRequest;
 use Symfony\Component\HttpFoundation\Cookie;
 use Symfony\Component\HttpFoundation\Request as SymfonyRequest;
+use Symfony\Component\HttpFoundation\Request;
```
Comment (andig) [inline Bridges/HttpKernel.php]: You have the SymfonyRequest already?

File: Bridges/HttpKernel.php [hunk 2]
```diff
@@ -150,9 +151,7 @@ protected function mapRequest(ReactRequest $reactRequest)
             session_id(Utils::generateSessionId());
         }
 
-        $_SERVER['PHP_AUTH_USER'] = '';
-        $_SERVER['PHP_AUTH_PW'] = '';
-        $_SERVER['AUTH_TYPE'] = '';
+        unset($headers['PHP_AUTH_USER'], $headers['PHP_AUTH_PW'], $headers['AUTH_TYPE']);
```
Comment (andig) [inline Bridges/HttpKernel.php]: Are these guaranteed to be set or will array access throw a warning?

File: Bridges/HttpKernel.php [hunk 3]
```diff
@@ -161,9 +160,9 @@ protected function mapRequest(ReactRequest $reactRequest)
             if (($type === 'Basic' || $type === 'Digest') && isset($authorizationHeaderParts[1])) {
                 $credentials = base64_decode($authorizationHeaderParts[1]);
                 $credentialsParts = explode(':', $credentials);
-                $_SERVER['PHP_AUTH_USER'] = isset($credentialsParts[0]) ? $credentialsParts[0] : '';
-                $_SERVER['PHP_AUTH_PW'] = isset($credentialsParts[1]) ? $credentialsParts[1] : '';
-                $_SERVER['AUTH_TYPE'] = $type;
+                $headers['PHP_AUTH_USER'] = isset($credentialsParts[0]) ? $credentialsParts[0] : '';
+                $headers['PHP_AUTH_PW'] = isset($credentialsParts[1]) ? $credentialsParts[1] : '';
+                $headers['AUTH_TYPE'] = $type;
             }
```
Comment (andig) [inline Bridges/HttpKernel.php]: This would be an addon: what about Bearer authentication? It is today in symfony only available from the apache headers. Any idea how to get those across?

File: Bridges/HttpKernel.php (hunk 2 above)
Comment (dzubchik) [inline Bridges/HttpKernel.php]: http://php.net/manual/en/function.unset.php#119711

**Comment by dzubchik** [comment]
@andig, @marcj  what do you think about implementing better headers parser in [react/http](https://github.com/reactphp/http/blob/master/src/RequestHeaderParser.php#L57)? Or we should [reset](https://github.com/php-pm/php-pm-httpkernel/issues/47#issuecomment-261296193) $_SERVER values in each request?

**Comment by dzubchik** [comment]
@marcj, @andig , I have a little updated this PR after seeing [this commit](https://github.com/php-pm/php-pm/commit/9b63b997f6cb1b5cfec650d22c46a99256eadbcd). Now it works correctly with headers and auth headers parsing is moving to symfony request. I removed line with headers merging, because I could not find any example when symfony and react headers could be different. If you insist, I will return that line. But all my previous code should be removed from this adapter.

File: Bridges/HttpKernel.php [hunk 4]
```diff
@@ -177,10 +157,10 @@ protected function mapRequest(ReactRequest $reactRequest)
             $class = '\Symfony\Component\HttpFoundation\Request';
         }
 
-        $syRequest = new $class($query, $post, $attributes = [], $cookies, $files, $_SERVER, $reactRequest->getBody());
+        /** @var SymfonyRequest $syRequest */
+        $syRequest = new $class($query, $post, $attributes = [], $_COOKIE, $files, $_SERVER, $reactRequest->getBody());
```
Comment (marcj) [inline Bridges/HttpKernel.php]: so you user and password in the symfony request with this change?

Comment (andig) [inline Bridges/HttpKernel.php]: Would it be possiblr to create a new, clean pr and describe the problem it tries to solve? Must say that I'm totally lost by now.

**Comment by dzubchik** [comment]
First, I've created PR https://github.com/php-pm/php-pm-httpkernel/pull/46 because headers from react request rewrite all headers from symfony request. Then, I've opened the first version of this PR, because of bug when during application runtime $ _SERVER is just increasing overtime, so the headers are not consistant with current request. But, @marcj had fixed this in https://github.com/php-pm/php-pm/commit/9b63b997f6cb1b5cfec650d22c46a99256eadbcd, so I've rewrote my PR, only to remove my old code with auth headers, because now Symfony request handle all of this correctly and remove $ cookie, because it is useless.

**Comment by marcj** [comment]
@dzubchik thanks, good job!
